spring:
  application:
    name: apiEscuelaEnLinea
  datasource:
    url: jdbc:postgresql://localhost:5430/escuela-en-linea-db
    username: arqui
    password: 2024
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate_config:
      ddl-auto: update

server:
  port: 8010
